# Project Description
Banks play a crucial role in market economies. They decide who can get finance and on what terms and can make or break investment decisions. For markets and society to function, individuals and companies need access to credit. 

Credit scoring algorithms, which make a guess at the probability of default, are the method banks use to determine whether or not a loan should be granted. This project requires participants to improve on the state of the art in credit scoring, by predicting the probability that somebody will experience financial distress in the next two years.

**You will need to:**
- Split your dataset as train(80%), dev(20%) and test(20%) sets.
- Explore the data: get the distribution of each feature, define anomalous value, check missing rates for columns in the dataset.
- Try different ways to deal with anomalous/missing value, and machine learning algorithms for classification
- Tunning parameters for machine learning algorithms
- Use cross validation to help you choose among different algorithms

In [1]:
# Package imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# load dataset
data = pd.read_csv('training_data.csv', encoding='utf-8', dtype={'Id':str})
data = data.set_index('Id', drop=True)

In [5]:
data.head(20)

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
Id,,,,,,,,,,,
00989128,0,0.038794,48,0,0.093447,4333.0,5,0,0,0,0.0
00466784,0,0.056980,85,0,0.025912,2083.0,3,0,0,0,0.0
00020283,0,0.015114,48,0,229.000000,1.0,7,0,1,1,3.0
00923225,0,0.160278,56,0,0.486425,1325.0,4,0,0,0,1.0
00143098,0,0.041472,69,0,72.000000,NaN,9,0,0,0,0.0
01099226,0,0.000000,74,0,3089.000000,NaN,9,0,1,0,0.0
00066056,0,0.230399,40,0,2033.000000,NaN,3,0,1,0,0.0
01498853,0,0.000000,25,0,520.000000,NaN,6,0,0,0,0.0
00316731,0,0.000000,61,0,1045.000000,NaN,6,0,1,0,0.0
00903329,0,0.376394,62,0,0.667688,5220.0,17,0,2,0,0.0
00620772,0,0.007875,62,0,0.260118,6250.0,6,0,2,0,0.0
00499546,0,0.164378,49,1,0.856978,16500.0,12,0,7,0,2.0
00183816,0,0.000196,44,0,2006.000000,1.0,6,0,2,0,0.0
00171377,0,0.023756,39,0,0.412235,2500.0,6,0,1,0,0.0
00716543,1,0.319970,34,2,1.353671,2900.0,13,1,1,0,0.0
00393643,0,0.377801,40,0,0.181248,3828.0,3,0,0,0,4.0
01043921,0,0.024393,49,0,0.157692,13500.0,6,0,2,0,0.0
00054695,0,0.000000,56,0,2427.000000,NaN,10,0,3,0,0.0
00928688,0,0.401381,43,0,0.342915,18750.0,11,0,3,0,3.0
00125692,0,0.009013,31,0,1514.000000,NaN,5,0,1,0,0.0